### ISSUE TITLE
Bug: If link # changes then the link does not update

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark-github#10]
For example, if you start off with:

```md
#123
```

It becomes

```md
[#123](https://github.com/wooorm/remark-github/issues/123)
```

However if you change the issue number it still has the same inaccurate link:

```md
[#456](https://github.com/wooorm/remark-github/issues/123)
```

**Comment by wooorm** [comment]
GitHub doesn’t change the link either, and allows that:

```markdown
[#123](https://github.com/wooorm/remark-github/issues/123)
[#456](https://github.com/wooorm/remark-github/issues/123)
```

Yields:

[#123](https://github.com/wooorm/remark-github/issues/123)
[#456](https://github.com/wooorm/remark-github/issues/123)

**Comment by wooorm** [comment]
This is a feature, not a bug.
